version: 2.1.1.{build}
image: Visual Studio 2017
skip_tags: true

branches:
  only:
  - master
  - development

deploy:
- provider: NuGet
  api_key:
    secure: tRU8M11vrr1xpuhdmBSOSSjQZXAEQVGHR1dP+f/c+RkA1+ZJqCDY2Rsv9Nk4okeT
  on:
    branch: master

- provider: GitHub
  release: Pubg.Net-v$(appveyor_build_version)
  description: ''
  auth_token:
    secure: 6bQdMR64k8Hsx3yyvLjkfD9K16vBFYQg85PqD5tAypkcBRe8cSsofZAgavw1QrVm
  artifact: /.*\.nupkg/            
  draft: false
  prerelease: false
  on:
    branch: master
  

before_build:
  - dotnet --info
  - ps: Write-Host $("Performing Dot Net Restore")
  - dotnet restore

build:
  parallel: true

build_script:
  - ps: Write-Host $("Performing build")
  - dotnet build -c Release src\pubg-dotnet
  - dotnet build -c Debug src\pubg-dotnet
  - dotnet build -c Debug test\pubg-dotnet.Tests

after_build:
  - ps: Write-Host $("Performing dotnet pack")
  - dotnet pack -c Release src\pubg-dotnet

test_script:
  - ps: Write-Host $("Starting tests")
  - ps: Write-Host $("Running full tests")
  - dotnet test test\pubg-dotnet.Tests\pubg-dotnet.Tests.csproj
  - ps: Write-Host $("Running unit tests")
  - dotnet test test\pubg-dotnet.UnitTests\pubg-dotnet.UnitTests.csproj

artifacts:
  - path: '**\*.nupkg'
